name: Release new version on WordPress.org
on:
  push:
    tags:
    - "*"
jobs:
  tag:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install PHP dependencies
      run: composer install
    - name: Build
      run: |
        npm install
        npm run build
        npm run css
    - uses: 10up/action-wordpress-plugin-deploy@master
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
