name: Release new version on WordPress.org
on:
  push:
    tags:
    - "*"
jobs:
  tag:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install PHP dependencies
      run: composer install
    - name: Build
      run: |
        npm install
        npm run build
        npm run css
    - uses: 10up/action-wordpress-plugin-deploy@master
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
    - name: Set env
      run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF#refs/*/}
    - name: Notify Slack
      run: |
        curl -X POST --data-urlencode "payload={\"channel\": \"#meta-box\", \"username\": \"Bot\", \"text\": \"New version $RELEASE_VERSION for MB Custom Post Type has been just released!\", \"icon_emoji\": \":tada:\"}" ${{ secrets.SLACK_WEBHOOK }}
